[[redirects]]
  from = "/gemini/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200

[[redirects]]
  from = "/detect/*"
  to = "https://detect.liccsu.com/:splat"
  status = 200

[[redirects]]
  from = "/github/*"
  to = "https://github.com/:splat"
  status = 200
